# This file was generated by GoReleaser. DO NOT EDIT.
class Vizix < Formula
  desc "vizix - Software to create fun and profit"
  homepage ""
  version "0.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/vs4vijay/vizix/releases/download/v0.0.0/vizix_0.0.0_Darwin_x86_64.tar.gz"
    sha256 "0c1e60636403421fdbc52e00674f025be57ab11f40dbad23906d8662f62c1dd3"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/vs4vijay/vizix/releases/download/v0.0.0/vizix_0.0.0_Linux_x86_64.tar.gz"
      sha256 "e961b75a9f28183726f81f2894c02ceeaf0e51235470f34c9d1f2bb926256562"
    end
  end

  def install
    bin.install "vizix"
  end

  test do
    system "#{bin}/vizix --version"
  end
end
