# This file was generated by GoReleaser. DO NOT EDIT.
class Vizix < Formula
  desc "vizix - Software to create fun and profit"
  homepage ""
  version "0.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/vs4vijay/vizix/releases/download/v0.0.0/vizix_0.0.0_mac`_x86_64.tar.gz"
    sha256 "ebc46549d19bdb9465104565b2f81df27269b98b9bfe524e6c169864c47e8106"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/vs4vijay/vizix/releases/download/v0.0.0/vizix_0.0.0_linux_x86_64.tar.gz"
      sha256 "0db5182eabcff607e596c887ed1218f86a2bb9cb118eb8a269a749c479e4dc36"
    end
  end

  def install
    bin.install "vizix"
  end

  test do
    system "#{bin}/vizix --version"
  end
end
